console.log('Question 2');
let arr=[100,'fruits',2.5,'games'];
console.log("Array1:"+arr);

console.log("Array1 length:"+arr.length);
console.log("Array1 to string:"+arr.toString());
var v1=arr.join(" - ");
console.log("Join:"+v1);
console.log("pop:"+arr.pop());
arr.push("hotstar");
console.log("push hotstar:"+arr);
console.log("shift:"+arr.shift());
console.log("unshift:"+arr.unshift(567));
arr.splice(2,0,"RED","BLUE");
console.log("splice:"+arr);
let arr2=[200,'orange',7.8];
console.log("Array2:"+arr2);
let arr3=arr.concat(arr2);
console.log("concat:"+arr3);
console.log("------------------------------------------------");
let str1="     Learning methods in Javascript ";
console.log("String is:"+str1);
console.log("index of i:"+str1.indexOf("i"));
console.log("last index of i:"+str1.lastIndexOf("i"));
console.log("search 'in':"+str1.search("in"));
let str2=str1.slice(4,5);
console.log("slice:"+str2);
let str3=str1.substring(10,15);
console.log("substring 10-15:"+str3);
console.log("replace learning by studying:"+str1.replace("Learning","Studying"));
let new1=str1.trim();
console.log("trim:"+new1);
console.log("charAt 15:"+new1.charAt(15));
let str4="Lets start";
let str5=str4.concat(" ",new1);
console.log("concat:"+str5);
console.log("split by space:"+str5.split(" "));